# Generated by Django 5.1.3 on 2024-11-28 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('due_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('customs', 'Customs Document'), ('internal', 'Internal Document'), ('shipment', 'Shipment Document')], max_length=100)),
                ('upload', models.FileField(upload_to='documents/')),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('reference', 'Reference'), ('duplicate', 'Duplicate')], max_length=100)),
                ('from_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_from', to='core.document')),
                ('to_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_to', to='core.document')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField()),
                ('file', models.FileField(upload_to='document_versions/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core.document')),
            ],
        ),
        migrations.CreateModel(
            name='MetadataSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_keywords', models.TextField()),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata_search', to='core.document')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_id', models.CharField(max_length=50, unique=True)),
                ('client_name', models.CharField(max_length=255)),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('customs_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('cleared', 'Cleared'), ('delayed', 'Delayed')], default='not_started', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('associated_documents', models.ManyToManyField(blank=True, related_name='shipments', to='core.document')),
            ],
        ),
    ]
